services:
  - type: web
    name: rubicks-cube
    env: python
    plan: free
    branch: main  
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --reload"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
